create database QLKS1
go
use QLKS1

go

CREATE TABLE NHANVIEN
(
	MANV NVARCHAR(10) PRIMARY KEY,
	HOTENNV NVARCHAR(100),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	DIACHI NVARCHAR(50),
	PHONE NVARCHAR(20),
	USERNAME NVARCHAR(100) UNIQUE,
	PASS VARCHAR(100) NOT NULL,
)
go
CREATE TABLE KHACHHANG
(
	MAKH NVARCHAR(10) PRIMARY KEY,
	HOTENKH NVARCHAR(100),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(10),
	DIACHI NVARCHAR(50),
	PHONE NVARCHAR(20),
	CMND NVARCHAR(20),
	QUOCTICH NVARCHAR(20)
)
GO

CREATE TABLE LOAIPHONG
(
	IDLOAI INT PRIMARY KEY IDENTITY,
	TENLOAI NVARCHAR(50)
)
GO
CREATE TABLE TINHTRANG
(
	IDTTRANG INT PRIMARY KEY IDENTITY,
	TENTTRANG NVARCHAR(50)
)
GO
CREATE TABLE PHONG
(
	MAPHG NVARCHAR(10) PRIMARY KEY,
	LOAIPHG INT NOT NULL,
	TTRANG INT NOT NULL,
	GIA MONEY,
	ROLL INT DEFAULT 0,
	FOREIGN	KEY(LOAIPHG) REFERENCES dbo.LOAIPHONG(IDLOAI),
	FOREIGN	KEY(TTRANG) REFERENCES dbo.TINHTRANG(IDTTRANG)
)

GO

CREATE TABLE HOADON
(
	MAHOADON INT PRIMARY KEY IDENTITY,
	MANV NVARCHAR(10) NOT NULL,
	MAPHG NVARCHAR(10) NOT NULL,
	MAKH NVARCHAR(10) NOT NULL,
	NGAYDK DATE,
	NGAYKT DATE NULL,
	FOREIGN	KEY(MANV) REFERENCES dbo.NHANVIEN(MANV),
	FOREIGN	KEY(MAPHG) REFERENCES dbo.PHONG(MAPHG),
	FOREIGN	KEY(MAKH) REFERENCES dbo.KHACHHANG(MAKH),
)
ALTER TABLE HOADON
DROP Column Display;
	


ALTER TABLE HOADON
  ADD CONSTRAINT DEFAULT_0
  DEFAULT 0 FOR Display;
GO



select * from HOADON where MAPHG 



select MANV, HOTENNV, NGAYSINH, GIOITINH, DIACHI, PHONE,USERNAME,PASS  from NHANVIEN where MANV like '% %'

select * from PHONG

select P.MAPHG,T.TENTTRANG, L.TENLOAI, P.GIA, P.ROLL
from PHONG P, TINHTRANG T, LOAIPHONG L
where T.TENTTRANG in(select TENTTRANG from TINHTRANG where IDTTRANG like P.TTRANG)
and L.TENLOAI in (select TENLOAI from LOAIPHONG where IDLOAI like P.LOAIPHG)
order by MAPHG


iNSERT INTO HOADON(MANV,MAPHG,MAKH,NGAYDK,NGAYKT)
values('001','b101','KH01','06/28/2022','06/30/2002')


INSERT INTO NHANVIEN(MANV, HOTENNV,GIOITINH,NGAYSINH,  DIACHI, PHONE , USERNAME, PASS) 
values('012',N'Tr?n Thanh Bình',N'Nam',N'2002/09/02',N'Ti?n Giang',N'0383785499',N'admin4',N'123')


INSERT INTO NHANVIEN(MANV, HOTENNV,GIOITINH,NGAYSINH,  DIACHI, PHONE , USERNAME, PASS) 
values('00s22a',N'Tr?n Thanh Bình',N'Nam',N'2002/09/02',N'Ti?n Giang',N'0383785499',N'admi2n1eq','')
INSERT INTO NHANVIEN(MANV, HOTENNV,GIOITINH,NGAYSINH,  DIACHI, PHONE , USERNAME, PASS) 
values('002a',N'Tr?n Thanh Bình',N'Nam',N'2002/09/02',N'Ti?n Giang',N'0383785499',N'admin1e',N'queque1')


select * from NHANVIEN where USERNAME = 'admin' and PASS = '123' 
 
 

 select P.MAPHG,N.HOTENNV,K.HOTENKH,L.TENLOAI, P.GIA, H.NGAYDK ,H.NGAYKT,IIF(DATEDIFF(Day,H.NGAYDK,H.NGAYKT) = 0 , 1 , DATEDIFF(Day,H.NGAYDK,H.NGAYKT)) as SONGAYO , IIF(DATEDIFF(Day,H.NGAYDK,H.NGAYKT) = 0 , 1 , DATEDIFF(Day,H.NGAYDK,H.NGAYKT)) * P.GIA as TONG
 from HOADON H, NHANVIEN N, LOAIPHONG L , KHACHHANG K ,PHONG P 
 where
 P.MAPHG in (select MAPHG from PHONG where MAPHG like H.MAPHG) and 
 N.HOTENNV in(select HOTENNV from NHANVIEN where MANV like H.MANV) and 
 K.HOTENKH in (select HOTENKH from KHACHHANG where MAKH like H.MAKH) and
 L.TENLOAI in(select TENLOAI from LOAIPHONG where IDLOAI like P.LOAIPHG) and
 H.NGAYKT is not null and
 H.NGAYKT >=  H.NGAYDK



 select  MANV,MAPHG,MAKH,NGAYDK,NGAYKT from HOADON 
  select  * from HOADON ;
 insert into HOADON(MANV,MAPHG,MAKH,NGAYDK,NGAYKT) Values ('002','b103','KHVIP02','2022/7/6')
 select USERNAME, MANV, HOTENNV from NHANVIEN WHERE USERNAME = 'admin'

 Update PHONG set LOAIPHG =N'1',TTRANG =N'1',GIA = '2500.0000'WHERE MAPHG = 'P003'
 select * from PHONG

 delete from PHONG where MAPHG = 'P001123123'

 update HOADON set MANV = 'NV01' where MAHOADON = '1'

 Select * from HOADON 

 Delete from HOADON where MANV = 'NV01'

 select MAHOADON,MANV,MAKH,MAPHG,GIA,LOAIPHONG,NGAYDK,NGAYKT

 select TONG from HOADON
 
 
 Update KHACHHANG set HOTENKH = N'Lê Duong Nh?t Minh',GIOITINH =N'Nam',NGAYSINH = '2022/07/10',DIACHI =N'B?n Trex',PHONE=N'21651061',CMND=N'165103213',QUOCTICH= N'Vi?t Nam'WHERE MAKH = 'M003'



 ALTER TABLE HOADON
ADD TONG money not null DEFAULT(0);


